//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGUIStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGUIStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator.ResGUIStr", typeof(ResGUIStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © SAP 2014.
        /// </summary>
        public static string ABOUT_TRADE_MARK {
            get {
                return ResourceManager.GetString("ABOUT_TRADE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Report.
        /// </summary>
        public static string BTN_CONVERSION_REPORT {
            get {
                return ResourceManager.GetString("BTN_CONVERSION_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Configuration Area.
        /// </summary>
        public static string BTN_SHOW_HIDE_CONFIG_AREA {
            get {
                return ResourceManager.GetString("BTN_SHOW_HIDE_CONFIG_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File.
        /// </summary>
        public static string LABEL_CONFIG_FILE {
            get {
                return ResourceManager.GetString("LABEL_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.
        /// </summary>
        public static string LABEL_INPUT_FILE {
            get {
                return ResourceManager.GetString("LABEL_INPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string LABEL_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("LABEL_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SQL Converter.
        /// </summary>
        public static string MENU_ITEM_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ITEM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MENU_ITEM_EXIT {
            get {
                return ResourceManager.GetString("MENU_ITEM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string MENU_ITEM_FONT {
            get {
                return ResourceManager.GetString("MENU_ITEM_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Command Line.
        /// </summary>
        public static string MENU_ITEM_GENERATE_COMMAND_LINE {
            get {
                return ResourceManager.GetString("MENU_ITEM_GENERATE_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Converter.
        /// </summary>
        public static string MENU_ITEM_RUN_CONVERSION {
            get {
                return ResourceManager.GetString("MENU_ITEM_RUN_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Converter.
        /// </summary>
        public static string MENU_ITEM_RUN_CONVERTER {
            get {
                return ResourceManager.GetString("MENU_ITEM_RUN_CONVERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration File.
        /// </summary>
        public static string MENU_ITEM_SAVE_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_SAVE_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Output File.
        /// </summary>
        public static string MENU_ITEM_SAVE_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_SAVE_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Configuration File.
        /// </summary>
        public static string MENU_ITEM_SELECT_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_SELECT_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version {1}.
        /// </summary>
        public static string TITLE_ABOUT {
            get {
                return ResourceManager.GetString("TITLE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        public static string TITLE_COMMAND_LINE {
            get {
                return ResourceManager.GetString("TITLE_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Report.
        /// </summary>
        public static string TITLE_CONVERSION_REPORT {
            get {
                return ResourceManager.GetString("TITLE_CONVERSION_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Procedures.
        /// </summary>
        public static string TITLE_CREATE_PROC {
            get {
                return ResourceManager.GetString("TITLE_CREATE_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Output.
        /// </summary>
        public static string TITLE_FORMAT_OUTPUT {
            get {
                return ResourceManager.GetString("TITLE_FORMAT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.
        /// </summary>
        public static string TITLE_INPUT_FILE {
            get {
                return ResourceManager.GetString("TITLE_INPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string TITLE_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("TITLE_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration File.
        /// </summary>
        public static string TITLE_SAVE_CONFIG_FILE {
            get {
                return ResourceManager.GetString("TITLE_SAVE_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Configuration File.
        /// </summary>
        public static string TITLE_SELECT_CONFIG_FILE {
            get {
                return ResourceManager.GetString("TITLE_SELECT_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input File.
        /// </summary>
        public static string TITLE_SELECT_INPUT_FILE {
            get {
                return ResourceManager.GetString("TITLE_SELECT_INPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output File.
        /// </summary>
        public static string TITLE_SELECT_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("TITLE_SELECT_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string TITLE_SERVER_NAME {
            get {
                return ResourceManager.GetString("TITLE_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Conversion Comments.
        /// </summary>
        public static string TITLE_SHOW_CONVERSION_COMMENTS {
            get {
                return ResourceManager.GetString("TITLE_SHOW_CONVERSION_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Converter.
        /// </summary>
        public static string TITLE_SQL_CONVERTER_NAME {
            get {
                return ResourceManager.GetString("TITLE_SQL_CONVERTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Case Fixer.
        /// </summary>
        public static string TITLE_USE_CASEFIXER {
            get {
                return ResourceManager.GetString("TITLE_USE_CASEFIXER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB User Name.
        /// </summary>
        public static string TITLE_USER_NAME {
            get {
                return ResourceManager.GetString("TITLE_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB User Password.
        /// </summary>
        public static string TITLE_USER_PASSWD {
            get {
                return ResourceManager.GetString("TITLE_USER_PASSWD", resourceCulture);
            }
        }
    }
}
