//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator.ResStr", typeof(ResStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version {1}.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name {0} was changed to {1}.
        /// </summary>
        public static string CF_COLUMN_NAME_FIXED {
            get {
                return ResourceManager.GetString("CF_COLUMN_NAME_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} not found in given tables.
        /// </summary>
        public static string CF_COLUMN_NOT_FOUND {
            get {
                return ResourceManager.GetString("CF_COLUMN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint {0} not found in given tables.
        /// </summary>
        public static string CF_CONSTRAINT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CF_CONSTRAINT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name {1} was changed to {2}.
        /// </summary>
        public static string CF_OBJECT_NAME_FIXED {
            get {
                return ResourceManager.GetString("CF_OBJECT_NAME_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} not found in given schemas.
        /// </summary>
        public static string CF_OBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CF_OBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support {0} clause with CREATE TABLE.
        /// </summary>
        public static string CLAUSE_NOT_IN_CREATE_TABLE {
            get {
                return ResourceManager.GetString("CLAUSE_NOT_IN_CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Statements in the input file contain errors; conversion was canceled.
        /// </summary>
        public static string ERR_CRITICAL_SYNTAX_ERROR {
            get {
                return ResourceManager.GetString("ERR_CRITICAL_SYNTAX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic creation of stored procedures in case of complex queries.
        /// </summary>
        public static string INF_AUTO_SP_FOR_COMPLEX_QUERIES {
            get {
                return ResourceManager.GetString("INF_AUTO_SP_FOR_COMPLEX_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a command line string from configuration file only.
        /// </summary>
        public static string INF_CREATE_COMMAND_LINE {
            get {
                return ResourceManager.GetString("INF_CREATE_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display help.
        /// </summary>
        public static string INF_DISPLAY_HELP {
            get {
                return ResourceManager.GetString("INF_DISPLAY_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable case fixer.
        /// </summary>
        public static string INF_ENABLE_CASE_FIXER_ALGORITHM {
            get {
                return ResourceManager.GetString("INF_ENABLE_CASE_FIXER_ALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable formatter.
        /// </summary>
        public static string INF_ENABLE_FORMATTER {
            get {
                return ResourceManager.GetString("INF_ENABLE_FORMATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter -i input.sql -o output.sql.
        /// </summary>
        public static string INF_EXAMPLE_1ST_LINE {
            get {
                return ResourceManager.GetString("INF_EXAMPLE_1ST_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter -c -f -i input.sql -o output.sql.
        /// </summary>
        public static string INF_EXAMPLE_2ND_LINE {
            get {
                return ResourceManager.GetString("INF_EXAMPLE_2ND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        public static string INF_EXAMPLES {
            get {
                return ResourceManager.GetString("INF_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude conversion comments from the output file.
        /// </summary>
        public static string INF_EXCLUDE_TOOLS_COMMENTS_IN_OUTPUT {
            get {
                return ResourceManager.GetString("INF_EXCLUDE_TOOLS_COMMENTS_IN_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use graphic user interface..
        /// </summary>
        public static string INF_GUI {
            get {
                return ResourceManager.GetString("INF_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL database.
        /// </summary>
        public static string INF_MS_DATABASE {
            get {
                return ResourceManager.GetString("INF_MS_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL database password.
        /// </summary>
        public static string INF_MS_PWD {
            get {
                return ResourceManager.GetString("INF_MS_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL database server name.
        /// </summary>
        public static string INF_MS_SERVER_NAME {
            get {
                return ResourceManager.GetString("INF_MS_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL database user name.
        /// </summary>
        public static string INF_MS_USER_NAME {
            get {
                return ResourceManager.GetString("INF_MS_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to input Transact SQL file.
        /// </summary>
        public static string INF_PATH_TO_INPUT {
            get {
                return ResourceManager.GetString("INF_PATH_TO_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to output SAP HANA SQL file.
        /// </summary>
        public static string INF_PATH_TO_OUTPUT {
            get {
                return ResourceManager.GetString("INF_PATH_TO_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to token Transact SQL file.
        /// </summary>
        public static string INF_PATH_TO_TOKEN {
            get {
                return ResourceManager.GetString("INF_PATH_TO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print version.
        /// </summary>
        public static string INF_PRINT_VERSION {
            get {
                return ResourceManager.GetString("INF_PRINT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA database password.
        /// </summary>
        public static string INF_SAP_HANA_PWD {
            get {
                return ResourceManager.GetString("INF_SAP_HANA_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA schema.
        /// </summary>
        public static string INF_SAP_HANA_SCHEMA {
            get {
                return ResourceManager.GetString("INF_SAP_HANA_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA database server name.
        /// </summary>
        public static string INF_SAP_HANA_SERVER_NAME {
            get {
                return ResourceManager.GetString("INF_SAP_HANA_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA database user name.
        /// </summary>
        public static string INF_SAP_HANA_USER_NAME {
            get {
                return ResourceManager.GetString("INF_SAP_HANA_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported options:.
        /// </summary>
        public static string INF_SUPPORTED_OPTIONS {
            get {
                return ResourceManager.GetString("INF_SUPPORTED_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Transact SQL statements to SAP HANA SQL statements.
        /// </summary>
        public static string INF_TRANSLATE_TSQL_INTO_HANA {
            get {
                return ResourceManager.GetString("INF_TRANSLATE_TSQL_INTO_HANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter &lt;options&gt;.
        /// </summary>
        public static string INF_TRANSLATOR_OPTIONS {
            get {
                return ResourceManager.GetString("INF_TRANSLATOR_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating input file, please wait....
        /// </summary>
        public static string INF_TRANSLATOR_RUNNING {
            get {
                return ResourceManager.GetString("INF_TRANSLATOR_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        public static string INF_USAGE {
            get {
                return ResourceManager.GetString("INF_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression for variables in statements.
        /// </summary>
        public static string INF_VARTOKEN {
            get {
                return ResourceManager.GetString("INF_VARTOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDEV was changed to STDDEV.
        /// </summary>
        public static string MOD_STDEV_TO_STDDEV {
            get {
                return ResourceManager.GetString("MOD_STDEV_TO_STDDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case fixing identifiers.
        /// </summary>
        public static string MSG_CASEFIXING_STEP {
            get {
                return ResourceManager.GetString("MSG_CASEFIXING_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns that cannot be found during verification:.
        /// </summary>
        public static string MSG_COLUMNS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_COLUMNS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the configuration file.
        /// </summary>
        public static string MSG_CONFIG_FILE_NOT_SAVED {
            get {
                return ResourceManager.GetString("MSG_CONFIG_FILE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of TSQL queries into SQL Script:.
        /// </summary>
        public static string MSG_CONVERSION_STAGE {
            get {
                return ResourceManager.GetString("MSG_CONVERSION_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement conversion.
        /// </summary>
        public static string MSG_CONVERSION_STEP {
            get {
                return ResourceManager.GetString("MSG_CONVERSION_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of corrected DB objects in the SAP HANA database:.
        /// </summary>
        public static string MSG_CORRECTED_IDENTIFIERS {
            get {
                return ResourceManager.GetString("MSG_CORRECTED_IDENTIFIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of input statements, conversions and converted statements may differ..
        /// </summary>
        public static string MSG_DIFFERENT_STATEMENTS_COUNT {
            get {
                return ResourceManager.GetString("MSG_DIFFERENT_STATEMENTS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of errors or limitations:.
        /// </summary>
        public static string MSG_ERRORS_LIMITATIONS {
            get {
                return ResourceManager.GetString("MSG_ERRORS_LIMITATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the input file.
        /// </summary>
        public static string MSG_INPUT_FILE_NOT_SAVED {
            get {
                return ResourceManager.GetString("MSG_INPUT_FILE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file {0} not found.
        /// </summary>
        public static string MSG_INPUT_FILE_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_INPUT_FILE_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input statements found: .
        /// </summary>
        public static string MSG_INPUT_STATEMENTS_FOUND {
            get {
                return ResourceManager.GetString("MSG_INPUT_STATEMENTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0}.
        /// </summary>
        public static string MSG_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("MSG_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration option &quot;{0}&quot;.
        /// </summary>
        public static string MSG_INVALID_CONFIG_OPTIONS {
            get {
                return ResourceManager.GetString("MSG_INVALID_CONFIG_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input file name &quot;{0}&quot;.
        /// </summary>
        public static string MSG_INVALID_INPUT_FILE_NAME {
            get {
                return ResourceManager.GetString("MSG_INVALID_INPUT_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter &quot;{0}&quot;.
        /// </summary>
        public static string MSG_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("MSG_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token option &quot;{0}&quot;.
        /// </summary>
        public static string MSG_INVALID_TOKEN_OPTIONS {
            get {
                return ResourceManager.GetString("MSG_INVALID_TOKEN_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &quot;{0}&quot; for boolean configuration option &quot;{1}&quot;; use &quot;true&quot; or &quot;false&quot;.
        /// </summary>
        public static string MSG_INVALID_VALUE_FOR_BOOLEAN {
            get {
                return ResourceManager.GetString("MSG_INVALID_VALUE_FOR_BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema &quot;{0}&quot; does not exist in the SAP HANA database server {1}.
        /// </summary>
        public static string MSG_MISSING_SCHEMA_ON_SERVER {
            get {
                return ResourceManager.GetString("MSG_MISSING_SCHEMA_ON_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found; only input arguments will be processed.
        /// </summary>
        public static string MSG_NO_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSG_NO_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token file not found; variables will not be correctly matched to their values.
        /// </summary>
        public static string MSG_NO_TOKEN_FILE {
            get {
                return ResourceManager.GetString("MSG_NO_TOKEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value provided for parameter {0}.
        /// </summary>
        public static string MSG_NO_VALUE_PROVIDED_FOR_PARAM {
            get {
                return ResourceManager.GetString("MSG_NO_VALUE_PROVIDED_FOR_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of statements converted with errors or limitations: {0}.
        /// </summary>
        public static string MSG_NUM_OF_NOK_QUERIES {
            get {
                return ResourceManager.GetString("MSG_NUM_OF_NOK_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of statements converted without warnings or errors: {0}.
        /// </summary>
        public static string MSG_NUM_OF_OK_QUERIES {
            get {
                return ResourceManager.GetString("MSG_NUM_OF_OK_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of statements: {0}.
        /// </summary>
        public static string MSG_NUM_OF_QUERIES {
            get {
                return ResourceManager.GetString("MSG_NUM_OF_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the output file.
        /// </summary>
        public static string MSG_OUTPUT_FILE_NOT_SAVED {
            get {
                return ResourceManager.GetString("MSG_OUTPUT_FILE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string MSG_PRESS_ANY_KEY_TO_CONTINUE {
            get {
                return ResourceManager.GetString("MSG_PRESS_ANY_KEY_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the datetime2 or time type was removed.
        /// </summary>
        public static string MSG_REMOVED_LENGTHS_FOR_DATETIME2 {
            get {
                return ResourceManager.GetString("MSG_REMOVED_LENGTHS_FOR_DATETIME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan input statements.
        /// </summary>
        public static string MSG_SCAN_INPUT_STATEMENTS {
            get {
                return ResourceManager.GetString("MSG_SCAN_INPUT_STATEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database password missing.
        /// </summary>
        public static string MSG_SERVER_DBPASSWD_MISSING {
            get {
                return ResourceManager.GetString("MSG_SERVER_DBPASSWD_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema name missing.
        /// </summary>
        public static string MSG_SERVER_DBSCHEMA_MISSING {
            get {
                return ResourceManager.GetString("MSG_SERVER_DBSCHEMA_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name missing.
        /// </summary>
        public static string MSG_SERVER_DBSERVER_MISSING {
            get {
                return ResourceManager.GetString("MSG_SERVER_DBSERVER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify database user name.
        /// </summary>
        public static string MSG_SERVER_DBUSER_MISSING {
            get {
                return ResourceManager.GetString("MSG_SERVER_DBUSER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the SAP HANA DB server; specify databse settings:.
        /// </summary>
        public static string MSG_SERVER_PARAMETER_MISSING {
            get {
                return ResourceManager.GetString("MSG_SERVER_PARAMETER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support statement at {0}: {1}.
        /// </summary>
        public static string MSG_STATEMENT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MSG_STATEMENT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of features that are not supported by the converter:.
        /// </summary>
        public static string MSG_SUMINFO_UNSUPPORTED_FEATURES {
            get {
                return ResourceManager.GetString("MSG_SUMINFO_UNSUPPORTED_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical info:.
        /// </summary>
        public static string MSG_TECHNICAL_INFO {
            get {
                return ResourceManager.GetString("MSG_TECHNICAL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting statement {0} (out of {1})....
        /// </summary>
        public static string MSG_TRANSLATING_QUERY {
            get {
                return ResourceManager.GetString("MSG_TRANSLATING_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot verify DB objects in queries against existing DB objects in the SAP HANA database..
        /// </summary>
        public static string MSG_UNABLE_TO_VERIFY_IDENTFIERS {
            get {
                return ResourceManager.GetString("MSG_UNABLE_TO_VERIFY_IDENTFIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use ALL to cover all indexes of the given table; use specific index name.
        /// </summary>
        public static string NO_ALL_INDEXES {
            get {
                return ResourceManager.GetString("NO_ALL_INDEXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support statement ALTER PROCEDURE.
        /// </summary>
        public static string NO_ALTER_STATEMENT {
            get {
                return ResourceManager.GetString("NO_ALTER_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the ALTER VIEW statement; delete existing view and create a new one.
        /// </summary>
        public static string NO_ALTER_VIEW {
            get {
                return ResourceManager.GetString("NO_ALTER_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the AS clause.
        /// </summary>
        public static string NO_AS_CLAUSE {
            get {
                return ResourceManager.GetString("NO_AS_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the AS FileTable.
        /// </summary>
        public static string NO_AS_FILETABLE {
            get {
                return ResourceManager.GetString("NO_AS_FILETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW in SAP HANA does not support attributes ENCRYPTION, SCHEMABINDING, and VIEW_METADATA.
        /// </summary>
        public static string NO_ATTRIBUTE_IN_CREATE_VIEW {
            get {
                return ResourceManager.GetString("NO_ATTRIBUTE_IN_CREATE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA dose not support bitwise operator OR.
        /// </summary>
        public static string NO_BITWISE_OR_OPERATOR {
            get {
                return ResourceManager.GetString("NO_BITWISE_OR_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support bitwise operator XOR.
        /// </summary>
        public static string NO_BITWISE_XOR_OPERATOR {
            get {
                return ResourceManager.GetString("NO_BITWISE_XOR_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the FOR BROWSE clause.
        /// </summary>
        public static string NO_BROWSE_ON_HANA {
            get {
                return ResourceManager.GetString("NO_BROWSE_ON_HANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the CHANGE_TRACKING clause.
        /// </summary>
        public static string NO_CHANGE_TRACKING_CLAUSE {
            get {
                return ResourceManager.GetString("NO_CHANGE_TRACKING_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the CHECK or NO CHECK statement.
        /// </summary>
        public static string NO_CHECK_CLAUSE {
            get {
                return ResourceManager.GetString("NO_CHECK_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the WITH CHECK OPTION clause.
        /// </summary>
        public static string NO_CHECK_OPTION {
            get {
                return ResourceManager.GetString("NO_CHECK_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the DEFAULT VALUES clause.
        /// </summary>
        public static string NO_CLAUSE_DEFAULT_VALUES {
            get {
                return ResourceManager.GetString("NO_CLAUSE_DEFAULT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY KEY column constraint in SAP HANA does not support the CLUSTERED clause.
        /// </summary>
        public static string NO_CLUSTERED_CLAUSE_FOR_PRIMARY_KEY {
            get {
                return ResourceManager.GetString("NO_CLUSTERED_CLAUSE_FOR_PRIMARY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUE column constraint in SAP HANA does not support the CLUSTERED clause.
        /// </summary>
        public static string NO_CLUSTERED_FOR_UNIQUE_COLUMN {
            get {
                return ResourceManager.GetString("NO_CLUSTERED_FOR_UNIQUE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the CLUSTERED index.
        /// </summary>
        public static string NO_CLUSTERED_INDEX {
            get {
                return ResourceManager.GetString("NO_CLUSTERED_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support the COLLATE clause.
        /// </summary>
        public static string NO_COLLATE_CLAUSE {
            get {
                return ResourceManager.GetString("NO_COLLATE_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted does not support the COLLATE specification..
        /// </summary>
        public static string NO_COLLATE_SPECIFICATION {
            get {
                return ResourceManager.GetString("NO_COLLATE_SPECIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column constraint in SAP HANA does not support COLLATION.
        /// </summary>
        public static string NO_COLLATION_NOT_SUPPORTED_AS_COLUMN_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_COLLATION_NOT_SUPPORTED_AS_COLUMN_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column constraint in SAP HANA does not support {0}.
        /// </summary>
        public static string NO_COLUMN_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_COLUMN_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support MS SQL column constraint.
        /// </summary>
        public static string NO_COLUMN_CONSTRAINTS {
            get {
                return ResourceManager.GetString("NO_COLUMN_CONSTRAINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support {0}.
        /// </summary>
        public static string NO_COLUMN_DEFINITION {
            get {
                return ResourceManager.GetString("NO_COLUMN_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define columns in the PRIMARY KEY table constraint.
        /// </summary>
        public static string NO_COLUMNS_DEFINED_FOR_PK {
            get {
                return ResourceManager.GetString("NO_COLUMNS_DEFINED_FOR_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the COMPUTE clause.
        /// </summary>
        public static string NO_COMPUTE_ON_HANA {
            get {
                return ResourceManager.GetString("NO_COMPUTE_ON_HANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support computed column definition.
        /// </summary>
        public static string NO_COMPUTED_COLUMN {
            get {
                return ResourceManager.GetString("NO_COMPUTED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the computed column definition.
        /// </summary>
        public static string NO_COMPUTED_COLUMN_DEFINITION {
            get {
                return ResourceManager.GetString("NO_COMPUTED_COLUMN_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable cursor identifier does not exist in SAP HANA .
        /// </summary>
        public static string NO_CURSOR_AS_VARIABLE {
            get {
                return ResourceManager.GetString("NO_CURSOR_AS_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the usage of cursor in the WHERE clause.
        /// </summary>
        public static string NO_CURSOR_IN_WHERE_CLAUSE {
            get {
                return ResourceManager.GetString("NO_CURSOR_IN_WHERE_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support type datetimeoffset.
        /// </summary>
        public static string NO_DATETIMEOFFSET {
            get {
                return ResourceManager.GetString("NO_DATETIMEOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the DEALLOCATE statement.
        /// </summary>
        public static string NO_DEALLOCATE_STATEMENT {
            get {
                return ResourceManager.GetString("NO_DEALLOCATE_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support default values for PROCEDURE input parameters.
        /// </summary>
        public static string NO_DEFAULT_VALUES_PROCEDURE_INPUT_PARAMETERS {
            get {
                return ResourceManager.GetString("NO_DEFAULT_VALUES_PROCEDURE_INPUT_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the DESC and ASC indexes.
        /// </summary>
        public static string NO_DESC_FOR_INDEX {
            get {
                return ResourceManager.GetString("NO_DESC_FOR_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO statement does not support EXEC; use EXEC(&apos;insert into table &apos;+ originalstatement).
        /// </summary>
        public static string NO_EXEC_IN_INSERT {
            get {
                return ResourceManager.GetString("NO_EXEC_IN_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO statement does not support EXEC; put INSERT statement directly into stored procedure.
        /// </summary>
        public static string NO_EXEC_SP_IN_INSERT {
            get {
                return ResourceManager.GetString("NO_EXEC_SP_IN_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support the FILESTREAM clause.
        /// </summary>
        public static string NO_FILESTREAM_CLAUSE {
            get {
                return ResourceManager.GetString("NO_FILESTREAM_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the FILETABLE clause.
        /// </summary>
        public static string NO_FILETABLE_CLAUSE {
            get {
                return ResourceManager.GetString("NO_FILETABLE_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE index in SAP HANA does not support the FILESTREAM_ON clause.
        /// </summary>
        public static string NO_FILETSTREAM_ON_FOR_CREATE_INDEX {
            get {
                return ResourceManager.GetString("NO_FILETSTREAM_ON_FOR_CREATE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot define updatable columns for Cursor in SAP HANA.
        /// </summary>
        public static string NO_FOR_UPDATE_IN_CURSOR {
            get {
                return ResourceManager.GetString("NO_FOR_UPDATE_IN_CURSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support additional table sources in UPDATE/DELETE statement; manually rewrite the FROM clause for specifying JOIN to a subquery in WHERE clause.
        /// </summary>
        public static string NO_FROM_CLAUSE {
            get {
                return ResourceManager.GetString("NO_FROM_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support {0}.
        /// </summary>
        public static string NO_FUNCTION_BITWISENOT {
            get {
                return ResourceManager.GetString("NO_FUNCTION_BITWISENOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA supports only second, day, month, and year as parameters for DATEADD.
        /// </summary>
        public static string NO_FUNCTION_DATEADD {
            get {
                return ResourceManager.GetString("NO_FUNCTION_DATEADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA supports only day and second as parameters for DATEDIFF.
        /// </summary>
        public static string NO_FUNCTION_DATEDIFF {
            get {
                return ResourceManager.GetString("NO_FUNCTION_DATEDIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA supports only second, minute, hour, weekday, dayofyear, day, week, month, quarter, and year as parameters for DATENAME.
        /// </summary>
        public static string NO_FUNCTION_DATENAME {
            get {
                return ResourceManager.GetString("NO_FUNCTION_DATENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA supports only second, minute, hour, day, dw, dayofyear, week, month, and year as parameters for DATEPART.
        /// </summary>
        public static string NO_FUNCTION_DATEPART {
            get {
                return ResourceManager.GetString("NO_FUNCTION_DATEPART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the GROUPING function.
        /// </summary>
        public static string NO_FUNCTION_GROUPING {
            get {
                return ResourceManager.GetString("NO_FUNCTION_GROUPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support modulo function.
        /// </summary>
        public static string NO_FUNCTION_MODULO {
            get {
                return ResourceManager.GetString("NO_FUNCTION_MODULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support ranking function NTILE.
        /// </summary>
        public static string NO_FUNCTION_NTILE {
            get {
                return ResourceManager.GetString("NO_FUNCTION_NTILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures in SAP HANA does not support options in the TSQL functions.
        /// </summary>
        public static string NO_FUNCTION_OPTION {
            get {
                return ResourceManager.GetString("NO_FUNCTION_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support ranking function {0}.
        /// </summary>
        public static string NO_FUNCTION_RANKING {
            get {
                return ResourceManager.GetString("NO_FUNCTION_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures in SAP HANA does not support returning values using the TSQL functions.
        /// </summary>
        public static string NO_FUNCTION_RETURN_VALUE {
            get {
                return ResourceManager.GetString("NO_FUNCTION_RETURN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support function {0}.
        /// </summary>
        public static string NO_FUNCTION_SIMPLE_AGGR {
            get {
                return ResourceManager.GetString("NO_FUNCTION_SIMPLE_AGGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the GO statement.
        /// </summary>
        public static string NO_GO_STATEMENT {
            get {
                return ResourceManager.GetString("NO_GO_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support the IDENTITY clause.
        /// </summary>
        public static string NO_IDENTITY_CLAUSE {
            get {
                return ResourceManager.GetString("NO_IDENTITY_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE index in SAP HANA dose not support the INCLUDE clause.
        /// </summary>
        public static string NO_INCLUDE_CLAUSE {
            get {
                return ResourceManager.GetString("NO_INCLUDE_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support InsertTarget.
        /// </summary>
        public static string NO_INSERT_TARGET_IN_INSERT {
            get {
                return ResourceManager.GetString("NO_INSERT_TARGET_IN_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer used as argument in date function was converted to ADD_DAYS(&apos;1900-01-01 00:00:00.000&apos;, value); using integer as argument in date function will cause error in SAP HANA.
        /// </summary>
        public static string NO_INTEGER_AS_ARGUMENT_IN_DATE_FUNCTION {
            get {
                return ResourceManager.GetString("NO_INTEGER_AS_ARGUMENT_IN_DATE_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; unexpected data type.
        /// </summary>
        public static string NO_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("NO_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot execute queries on a linked DB server.
        /// </summary>
        public static string NO_LINKED_SERVER {
            get {
                return ResourceManager.GetString("NO_LINKED_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the LOCK_ESCALATION clause.
        /// </summary>
        public static string NO_LOCK_ESCALATION_CLAUSE {
            get {
                return ResourceManager.GetString("NO_LOCK_ESCALATION_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support module number in the EXEC statement.
        /// </summary>
        public static string NO_MODULE_NUMBER_IN_EXEC {
            get {
                return ResourceManager.GetString("NO_MODULE_NUMBER_IN_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support named transactions.
        /// </summary>
        public static string NO_NAMED_TRANSACTIONS {
            get {
                return ResourceManager.GetString("NO_NAMED_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support MS SQL column constraint.
        /// </summary>
        public static string NO_NONE_OF_MSSQL_COL_CONSTRAINT_SUPPORTED {
            get {
                return ResourceManager.GetString("NO_NONE_OF_MSSQL_COL_CONSTRAINT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE index in SAP HANA does not support the ON clause.
        /// </summary>
        public static string NO_ON_CLAUSE_FOR_CREATE_INDEX {
            get {
                return ResourceManager.GetString("NO_ON_CLAUSE_FOR_CREATE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support any specification including option {0} in REBUILD.
        /// </summary>
        public static string NO_OPTION_ALLOWED_IN_REBUILD {
            get {
                return ResourceManager.GetString("NO_OPTION_ALLOWED_IN_REBUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the OPTION clause.
        /// </summary>
        public static string NO_OPTION_CLAUSE {
            get {
                return ResourceManager.GetString("NO_OPTION_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure in SAP HANA does not support option {0}.
        /// </summary>
        public static string NO_OPTION_FOR_PROCEDURE {
            get {
                return ResourceManager.GetString("NO_OPTION_FOR_PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support options in the DROP INDEX statement.
        /// </summary>
        public static string NO_OPTIONS_FOR_DROP_INDEX {
            get {
                return ResourceManager.GetString("NO_OPTIONS_FOR_DROP_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the OUTPUT clause.
        /// </summary>
        public static string NO_OUTPUT_CLAUSE {
            get {
                return ResourceManager.GetString("NO_OUTPUT_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support parameters in the EXEC statement.
        /// </summary>
        public static string NO_PARAMS_IN_EXEC {
            get {
                return ResourceManager.GetString("NO_PARAMS_IN_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support percent in the TOP clause.
        /// </summary>
        public static string NO_PERCENT {
            get {
                return ResourceManager.GetString("NO_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length for datetime2 or time type was removed.
        /// </summary>
        public static string NO_PRECISION_LEN_IN_DATETIME {
            get {
                return ResourceManager.GetString("NO_PRECISION_LEN_IN_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY KEY column constraint in SAP HANA does not support {0}.
        /// </summary>
        public static string NO_PRIMARY_KEY_COLUMN_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_PRIMARY_KEY_COLUMN_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY KEY table constraint in SAP HANA does not support {0}.
        /// </summary>
        public static string NO_PRIMARY_KEY_TABLE_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_PRIMARY_KEY_TABLE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not contain functions for convertion between radians and degrees. Be careful for precision of conversion..
        /// </summary>
        public static string NO_RAD_DEG_FUNCTIONS {
            get {
                return ResourceManager.GetString("NO_RAD_DEG_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support setting seed number to RAND function.
        /// </summary>
        public static string NO_RAND_WITH_SEED {
            get {
                return ResourceManager.GetString("NO_RAND_WITH_SEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the REBUILD clause.
        /// </summary>
        public static string NO_REBUILD_CLAUSE {
            get {
                return ResourceManager.GetString("NO_REBUILD_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support option Recompile.
        /// </summary>
        public static string NO_RECOMPILE_ON_HANA {
            get {
                return ResourceManager.GetString("NO_RECOMPILE_ON_HANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support return variables in the EXEC statement.
        /// </summary>
        public static string NO_RET_VAR_IN_EXEC {
            get {
                return ResourceManager.GetString("NO_RET_VAR_IN_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support returning values using the RETURN statement.
        /// </summary>
        public static string NO_RETURN_VALUE {
            get {
                return ResourceManager.GetString("NO_RETURN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support the ROWGUIDCOL clause.
        /// </summary>
        public static string NO_ROWGUIDCOL_CLAUSE {
            get {
                return ResourceManager.GetString("NO_ROWGUIDCOL_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the SET clause.
        /// </summary>
        public static string NO_SET_CLAUSE {
            get {
                return ResourceManager.GetString("NO_SET_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support customizing the first weekday.
        /// </summary>
        public static string NO_SET_DATEFIRST {
            get {
                return ResourceManager.GetString("NO_SET_DATEFIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support setting global DATEFORMAT in separate SET statements.
        /// </summary>
        public static string NO_SET_DATEFORMAT {
            get {
                return ResourceManager.GetString("NO_SET_DATEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support setting {0}.
        /// </summary>
        public static string NO_SETTING_SUPPORTED {
            get {
                return ResourceManager.GetString("NO_SETTING_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support simple statements in triggers..
        /// </summary>
        public static string NO_SIMPLE_STATEMENTS_IN_TRIGGERS {
            get {
                return ResourceManager.GetString("NO_SIMPLE_STATEMENTS_IN_TRIGGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definition in SAP HANA does not support the SPARSE clause.
        /// </summary>
        public static string NO_SPARSE_CLAUSE {
            get {
                return ResourceManager.GetString("NO_SPARSE_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column constraint in SAP HANA does not support the SPARSE clause.
        /// </summary>
        public static string NO_SPARSE_NOT_SUPPORTED_AS_COLUMN_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_SPARSE_NOT_SUPPORTED_AS_COLUMN_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the SWITCH clause.
        /// </summary>
        public static string NO_SWITH_CLAUSE {
            get {
                return ResourceManager.GetString("NO_SWITH_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support table constraint {0}.
        /// </summary>
        public static string NO_TABLE_CONSTRAINT {
            get {
                return ResourceManager.GetString("NO_TABLE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support TABLE specification for identification of index; use unique index name in schema.
        /// </summary>
        public static string NO_TABLE_FOR_INDEX {
            get {
                return ResourceManager.GetString("NO_TABLE_FOR_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support table hints for query optimizer in TSQL.
        /// </summary>
        public static string NO_TABLE_HINTS {
            get {
                return ResourceManager.GetString("NO_TABLE_HINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the TABLESAMPLE feature in TSQL.
        /// </summary>
        public static string NO_TABLESAMPLE {
            get {
                return ResourceManager.GetString("NO_TABLESAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the TOP clause.
        /// </summary>
        public static string NO_TOP_CLAUSE {
            get {
                return ResourceManager.GetString("NO_TOP_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support WITH TIES in the TOP clause.
        /// </summary>
        public static string NO_TOP_WITH_TIES {
            get {
                return ResourceManager.GetString("NO_TOP_WITH_TIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the TRIGGER clause.
        /// </summary>
        public static string NO_TRIGGER_CLAUSE {
            get {
                return ResourceManager.GetString("NO_TRIGGER_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the TRY or CATCH statement.
        /// </summary>
        public static string NO_TRY_CATCH_STATEMENT {
            get {
                return ResourceManager.GetString("NO_TRY_CATCH_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support TSQL settings.
        /// </summary>
        public static string NO_TSQL_SETTINGS_SUPPORTED {
            get {
                return ResourceManager.GetString("NO_TSQL_SETTINGS_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support type hierarchyid.
        /// </summary>
        public static string NO_TYPE_HIERARCHYID {
            get {
                return ResourceManager.GetString("NO_TYPE_HIERARCHYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support type sql_variant.
        /// </summary>
        public static string NO_TYPE_SQL_VARIANT {
            get {
                return ResourceManager.GetString("NO_TYPE_SQL_VARIANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support type xml.
        /// </summary>
        public static string NO_TYPE_XML {
            get {
                return ResourceManager.GetString("NO_TYPE_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support UPDATE STATISTICS statements.
        /// </summary>
        public static string NO_UPDATE_STATISTICS {
            get {
                return ResourceManager.GetString("NO_UPDATE_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE index in SAP HANA does not support the WHERE clause.
        /// </summary>
        public static string NO_WHERE_CLAUSE_FOR_CREATE_INDEX {
            get {
                return ResourceManager.GetString("NO_WHERE_CLAUSE_FOR_CREATE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE in SAP HANA does not support WITH CHECK.
        /// </summary>
        public static string NO_WITH_CHECK_FOR_ALTER_TABLE {
            get {
                return ResourceManager.GetString("NO_WITH_CHECK_FOR_ALTER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE in SAP HANA does not support WITH CHECK.
        /// </summary>
        public static string NO_WITH_CHECK_NOT_SUPPORTED_FOR_ALTER_TABLE {
            get {
                return ResourceManager.GetString("NO_WITH_CHECK_NOT_SUPPORTED_FOR_ALTER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the TSQL WITH clause.
        /// </summary>
        public static string NO_WITH_CLAUSE {
            get {
                return ResourceManager.GetString("NO_WITH_CLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the WITH clause.
        /// </summary>
        public static string NO_WITH_ON_HANA {
            get {
                return ResourceManager.GetString("NO_WITH_ON_HANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the WITH option for dropping indexes.
        /// </summary>
        public static string NO_WITH_OPTIONS_FOR_DROP_INDEX {
            get {
                return ResourceManager.GetString("NO_WITH_OPTIONS_FOR_DROP_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER index in SAP HANA only allows operation REBUILD; {0} is not supported in ALTER INDEX.
        /// </summary>
        public static string ONLY_REBUILD_IN_ALTER_INDEX {
            get {
                return ResourceManager.GetString("ONLY_REBUILD_IN_ALTER_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support type {0}.
        /// </summary>
        public static string TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter does not support type {0}.
        /// </summary>
        public static string TYPE_NOT_SUPPORTED_BY_STRINGIFIER {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED_BY_STRINGIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP statements for multiple tables have been divided into separate DROP statements.
        /// </summary>
        public static string WARN_DROP_DIVIDED {
            get {
                return ResourceManager.GetString("WARN_DROP_DIVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP index with multiple indexes have been divided into separate DROP indexes.
        /// </summary>
        public static string WARN_DROP_INDEX_DIVIDED {
            get {
                return ResourceManager.GetString("WARN_DROP_INDEX_DIVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the DROP INDEX statement inside PROCEDURE; use EXEC(&apos;DROP INDEX...&apos;).
        /// </summary>
        public static string WARN_DROP_INDEX_IN_PROC {
            get {
                return ResourceManager.GetString("WARN_DROP_INDEX_IN_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW with multiple views have been divided into separate DROP VIEW statements.
        /// </summary>
        public static string WARN_DROP_VIEW_DIVIDED {
            get {
                return ResourceManager.GetString("WARN_DROP_VIEW_DIVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FROM DUMMY if there is no FROM clause in the SELECT statement.
        /// </summary>
        public static string WARN_DUMMY_TABLE {
            get {
                return ResourceManager.GetString("WARN_DUMMY_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you use function as an argument for date function take care of handling result. Integer is converted as &apos;1900-01-01 00:00:00.000&apos; + value on MSSQL. Converting integer to date raises error on HANA..
        /// </summary>
        public static string WARN_FUNCTION_AS_ARGUMENT_IN_DATE_FUNCTIONS {
            get {
                return ResourceManager.GetString("WARN_FUNCTION_AS_ARGUMENT_IN_DATE_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the CREATE FUNCTION statement; CREATE FUNCTION was changed to CREATE PROCEDURE.
        /// </summary>
        public static string WARN_FUNCTION_CONVERTED_TO_PROC {
            get {
                return ResourceManager.GetString("WARN_FUNCTION_CONVERTED_TO_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT statements with values for multiple rows have been divided into separate insertions.
        /// </summary>
        public static string WARN_INSERT_DIVIDED {
            get {
                return ResourceManager.GetString("WARN_INSERT_DIVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0};converter will be closed.
        /// </summary>
        public static string WARN_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("WARN_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action found in ALTER TABLE statement.
        /// </summary>
        public static string WARN_NO_ACTION_IN_ALTER_TABLE {
            get {
                return ResourceManager.GetString("WARN_NO_ACTION_IN_ALTER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define columns in the PRIMARY KEY table constraint.
        /// </summary>
        public static string WARN_NO_COLUMNS_FOR_PRIMARY_KEY {
            get {
                return ResourceManager.GetString("WARN_NO_COLUMNS_FOR_PRIMARY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define columns in the CREATE TABLE statement.
        /// </summary>
        public static string WARN_NO_COLUMNS_IN_CREATE {
            get {
                return ResourceManager.GetString("WARN_NO_COLUMNS_IN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify column names in the CREATE index.
        /// </summary>
        public static string WARN_NO_COLUMNS_IN_CREATE_INDEX {
            get {
                return ResourceManager.GetString("WARN_NO_COLUMNS_IN_CREATE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify column names in the SELECT clause.
        /// </summary>
        public static string WARN_NO_COLUMNS_IN_SELECT {
            get {
                return ResourceManager.GetString("WARN_NO_COLUMNS_IN_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support function CONVERT; use the CAST function or implicit casting functions.
        /// </summary>
        public static string WARN_NO_FUNCTION_CONVERT {
            get {
                return ResourceManager.GetString("WARN_NO_FUNCTION_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify index names in the CREATE index.
        /// </summary>
        public static string WARN_NO_INDEX_NAME_IN_CREATE {
            get {
                return ResourceManager.GetString("WARN_NO_INDEX_NAME_IN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP HANA does not support the NONCLUSTERED keyword; all SAP HANA indexes are NONCLUSTERED.
        /// </summary>
        public static string WARN_NO_NONCLUSTERED {
            get {
                return ResourceManager.GetString("WARN_NO_NONCLUSTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify table names in the CREATE index.
        /// </summary>
        public static string WARN_NO_TABLE_NAME_IN_CREATE_INDEX {
            get {
                return ResourceManager.GetString("WARN_NO_TABLE_NAME_IN_CREATE_INDEX", resourceCulture);
            }
        }
    }
}
